### ISSUE TITLE
如设备过卡或服务器限制造成的问题

### ISSUE THREAD

**Issue by hotianbexuanto** [ProletariatRR/Slimefun-helper#2]
a...如果设备过卡好像会出现个错误可通过调整操作延迟tick来解决(?)​大概吧如果服务器限制了大概只能加操作的延迟来解决了吧?_(:з」∠)_

**Comment by hotianbexuanto** [comment]
a这个是错误日志的消息获取配方时出现的
[22:24:45] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.keypad.2", "file":"获取粘液配方_v3.1.1.js"}/INFO]: [STDERR]: TypeError: Cannot read property '0' of undefined
[22:24:45] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.keypad.2", "file":"获取粘液配方_v3.1.1.js"}/INFO]: [STDERR]: 	at <js> back_to_last_menu(获取粘液配方_v3.1.1.js:50:1483-1501)
[22:24:45] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.keypad.2", "file":"获取粘液配方_v3.1.1.js"}/INFO]: [STDERR]: 	at <js> :program(获取粘液配方_v3.1.1.js:246:7048-7066)
[22:24:45] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.keypad.2", "file":"获取粘液配方_v3.1.1.js"}/INFO]: [STDERR]: 	at org.graalvm.polyglot.Context.eval(Context.java:399)
[22:24:45] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.keypad.2", "file":"获取粘液配方_v3.1.1.js"}/INFO]: [STDERR]: 	at xyz.wagyourtail.jsmacros.js.language.impl.GraalLanguageDefinition.exec(GraalLanguageDefinition.java:97)
[22:24:45] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.keypad.2", "file":"获取粘液配方_v3.1.1.js"}/INFO]: [STDERR]: 	at xyz.wagyourtail.jsmacros.core.language.BaseLanguage.lambda$trigger$1(BaseLanguage.java:54)
[22:24:45] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.keypad.2", "file":"获取粘液配方_v3.1.1.js"}/INFO]: [STDERR]: 	at xyz.wagyourtail.jsmacros.core.threads.JsMacrosThreadPool$PoolThread.run(JsMacrosThreadPool.java:78)

**Comment by hotianbexuanto** [comment]
已经改tick改成4和8正常了就是不知道是不是设备问题读取配方就是有时候会读取到一半就断了保存了_(´ཀ`」 ∠)__
